export const paths = {
    root: '/',
    image: '/image',
    video: '/video',
    edit: '/edit',
    login: '/login',
    signup: '/signup',
    admin: '/admin',
    adminSupport: '/admin/support',
    profile: '/profile',
    publicProfile: '/profile/:userId',
    pricing: '/pricing',
    verifyEmail: '/verify-email',
    terms: '/terms',
    privacy: '/privacy',
    forgotPassword: '/forgot-password',
    resetPassword: '/reset-password',
};